import Header from "@/components/Header/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import Footer from "@/components/Footer/Footer";
import Providers from "./ThemeProvider";
import ThemProvider from "./ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`{$inter.className } flex`}>
        <div className="container-fluid flex darK:bg-red-500  justify-center w-screen h-auto items-center">
          <div className="row flex justify-center items-center w-full h-full ">
            <div className="col flex justify-between items-center  w-full h-full">
              <ThemProvider>
                <Header />
                {children}
              </ThemProvider>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
